# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.darkzach.com
title: Zach's not so private wiki
keywords: java, frontend, backend, css, javascript
description: you see the title..
author: Zach Tse
default_ext: md
pygments: true
theme: yasimple